---
- hosts: server
  gather_facts: no
  remote_user: userWithRootPrivileges
  become: yes
  become_method: sudo
  vars_files:
    - vars/server.yml
    - vars/common.yml
  roles:
    - server
    - git
    - nodejs
    - nginx
    - php
    - mysql
    - redis
    - beanstalkd
    - app
