---
server:
    packages: [htop, imagemagick, mc]
    timezone: Europe/Moscow
    locale: ru_RU.UTF-8
    home: "{{ server_home }}"
    dev: "{{ server_dev }}"
nginx:
    docroot: "{{ server_home }}/data/code/pub"
    servername: "{{ server_name }}"
php:
    ppa: "ppa:ondrej/php"
    packages: [php7.0-fpm, php7.0-cli, php7.0-dev, php7.0-sqlite3, php7.0-gd, php7.0-imagick, php7.0-curl, php7.0-mcrypt, php7.0-mysql, php7.0-readline, php7.0-mbstring, php7.0-xml, php7.0-zip, php7.0-intl, php7.0-bcmath, php7.0-soap]
mysql:
    database: magento
    root_password: "{{ mysql_root_password }}"
    user: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
