---
- name: Add ppa Repository
  apt_repository: repo=ppa:nginx/stable

- name: Update apt
  apt: update_cache=yes

- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Change default config
  template: src=nginx.conf.tpl dest=/etc/nginx/nginx.conf

- name: Change default myme types
  template: src=mime.types.tpl dest=/etc/nginx/mime.types

- name: Change default host for security reason
  template: src=default.tpl dest=/etc/nginx/sites-available/default

- name: Add nginx host
  template: src=site.tpl dest=/etc/nginx/sites-available/{{ server_name }}

- name: Create symlink
  file: src=/etc/nginx/sites-available/{{ server_name }} dest=/etc/nginx/sites-enabled/{{ server_name }} state=link
  notify: restart nginx
